version: "3.7"
services:
  db:
    image: postgres:12
    container_name: stock-db
    environment:
      - POSTGRES_USER=projectormato
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
      - POSTGRES_DB=stock_db
      - DATABASE_HOST=localhost
    volumes:
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
